name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Setup Python
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m nltk.downloader punkt
        python -m nltk.downloader averaged_perceptron_tagger

    # Run your Streamlit app (example)
    - name: Run Streamlit app
      run: |
        streamlit run app.py
